apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-api
  labels:
    app: patient-service-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-service-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: patient-service-api
    spec:
      containers:
        - name: patient-service-api-container
          image: patient-service-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: / # Adjust this if your health check endpoint differs
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: / # Adjust this if your health check endpoint differs
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: patient-service-api-service
  labels:
    app: patient-service-api
spec:
  selector:
    app: patient-service-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: patient-service-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: 'HTTP'
spec:
  rules:
    - host: patient-service-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: patient-service-api-service
                port:
                  number: 80
