name: Deploy to VPC Utrahost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Debug Secrets
      #   run: echo ${{ secrets.EC2_HOST }} ${{ secrets.EC2_USERNAME }}
      # - name: Test SSH connection
      #   run: |
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
      #     chmod 600 id_rsa
      #     ssh -i id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "echo Connected successfully"

      - name: Create .env file dynamically
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          echo "DB_HOST=${DB_HOST}" >> .env
          echo "DB_PORT=${DB_PORT}" >> .env
          echo "DB_USERNAME=${DB_USERNAME}" >> .env
          echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
          echo "DB_NAME=${DB_NAME}" >> .env

      - name: Transfer .env file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: '.env'
          target: '/home/ec2-user/meditrack'
          debug: true

      # - name: Set permissions
      #   run: |
      #     ssh -i id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} \
      #     "chmod 600 /home/ec2-user/meditrack/.env && chmod -R 755 /home/ec2-user/meditrack"

      - name: Transfer repository files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: '.'
          target: '/home/ec2-user/meditrack'
          debug: true
