name: Deploy to VPC Utrahost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Secrets
        run: echo ${{ secrets.EC2_HOST }} ${{ secrets.EC2_USER_NAME }}
      - name: Test SSH connection
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa
          ssh -i id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER_NAME }}@${{ secrets.EC2_HOST }} "echo Connected successfully"

      - name: Create .env file dynamically
        env:
          ENV: ${{ secrets.ENV }}
          EC2_USER_NAME: ${{ secrets.EC2_USER_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DATABASE: ${{ secrets.DATABASE }}
        run: |
          echo "ENV=${ENV}" > .env
          echo "EC2_USERNAME=${EC2_USER_NAME}" >> .env
          echo "DB_HOST=${DB_HOST}" >> .env
          echo "DB_PORT=${DB_PORT}" >> .env
          echo "DB_USER=${DB_USER}" >> .env
          echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
          echo "DATABASE=${DATABASE}" >> .env

      - name: Transfer .env file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: '.env'
          target: '/home/ec2-user/meditrack/.env'
          debug: true
